crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from crmApp import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crm', include('crmApp.urls')),
    path('country/',include('countries.urls')),
    path('',include('flightbooking.urls')),
]

crm/crmApp/urls.py
from django.urls import path
from . import views
from .views import ack_agree, assign_plan, centersList, customer_authorization, pending_invoices, relatedBooking, send_signature_request, subscription_plans, update_booking_status
from .views import fetch_passenger_data,submit_refund_form,update_refund_status
from django.contrib.auth.views import LoginView
from .views import reassign_lead_agent


app_name = 'crmApp'

urlpatterns = [
    path('', views.login_view, name='login'),  # Assign 'login' as the name for the login view
    # path('base/', views.flight_book, name='base'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('total_booking/', views.total_booking, name='total_booking'),
    path('total_user/', views.total_user, name='total_user'),
    path('booking/', views.booking, name='booking'),
    path('refund/', views.refund, name='refund'),
    path('chargeback/', views.chargeback, name='chargeback'),
    path('rejected/', views.rejected, name='rejected'),
    path('mco/', views.mco, name='mco'),
    path('cancellation/', views.cancellation, name='cancellation'),
    path('ecredit/', views.ecredit, name='ecredit'),
    path('update_booking_status/', update_booking_status, name='update_booking_status'),
    path('fetch_passenger_data/', fetch_passenger_data, name='fetch_passenger_data'),
    path('submit_refund_form/', submit_refund_form, name='submit_refund_form'),
    path('get_location_suggestions/', views.get_location_suggestions, name='get_location_suggestions'),
    path('flight_results/', views.flight_results, name='flight_results'),
    path('update_refund_status/', update_refund_status, name='update_refund_status'),
    path('create_user/', views.create_user, name='create_user'),
    path('update_user/', views.update_user, name='update_user'),
    path('block_user/<int:user_id>/', views.block_user, name='block_user'),
    path('logout/', views.logout_view, name='logout'),
    # path('update_booking_statusT/', views.update_booking_statusT, name='update_booking_statusT'),
    path('delete_booking/', views.delete_booking, name='delete_booking'),
    path('book_view/', views.book_view, name='book_view'),
    path('generate-invoice/', views.generate_invoice, name='generate_invoice'),
    path('send-email/', views.send_email, name='send_email'),
    # path('invoice-success/', invoice_success, name='invoice_success'),
    path('sales/', views.sales_view, name='sales'),
    path('reassign/', reassign_lead_agent, name='reassign_lead_agent'),
    path('get_agent_data/', views.get_agent_data, name='get_agent_data'),
    path('check-availability/', views.check_flight, name='check-flight'),    
    path('submit_chargeback/', views.submit_chargeback, name='submit_chargeback'),
    path('update_chargeback_lead_status/', views.update_chargeback_lead_status, name='update_chargeback_lead_status'),
    path('update_chargeback_status/', views.update_chargeback_status, name='update_chargeback_status'),
    # path('chargeback-details/<int:chargeback_id>/', views.chargeback_details, name='chargeback_details'),
    path('invoice/', views.invoiceCreate, name='invoice'),
    path('submit-invoice/', views.submit_invoice, name='submit_invoice'),
    path('fetch-invoice/', views.invoice_details_fetch, name="invoice-details-fetch"),
    path('submit_form_customer/', views.submit_cutomer, name = 'submit_customer'),
    path('send-signature-request/', send_signature_request, name='send_signature_request'),
    path('pending_invoices/', pending_invoices, name='pending_invoices'),
    path('flight-search-multi/', views.flight_search_multi, name='multi_search'),
    path('payment/', views.payment, name='payment'), 
    path('related-booking/', relatedBooking, name='related_booking'),
    path('initiate-payment/', views.initiatePayment, name='initiatePayment'),
    path('invoice-form/', views.invoice_form, name="invocie_form"),
    path('gateway/', views.gateway, name='gateway'),
    path('centers/', centersList, name='centers_list'),
    path('add-center/', views.add_center, name='add_center'),
    path('centers/<int:id>/pdf/', views.view_pdf, name='view_pdf'),
    path('authorize_center/', views.authorize_center, name='authorize_center'),
    path('acknowledge/<int:center_id>/', views.ack_agree, name='ack_agree'),
    path('track/',views.track, name="track"),
    path('total_chargeback/',views.total_chargeback, name="total_chargeback"),
    path('total_leads/',views.total_leads, name="total_leads"),
    path('total_refund/',views.total_refund, name="total_refund"),
    path('new_booking/', views.new_booking, name='new_booking'),
    path('center-related/', views.center_related, name='center_related'),
    path('centers_related_booking/<str:center_name>/', views.centers_related_booking, name='centers_related_booking'),
    path('centers_related_pending/<str:center_name>/', views.centers_related_pending, name='centers_related_pending'),
    path('centers_related_confirmed/<str:center_name>/', views.centers_related_confirmed, name='centers_related_confirmed'),
    path('centers_related_cancel/<str:center_name>/', views.centers_related_cancel, name='centers_related_cancel'),
    path('centers_related_refund/<str:center_name>/', views.centers_related_refund, name='centers_related_refund'),
    path('income/',views.income, name="income"),
    path('centers_related_apiRequest/<str:center_name>/', views.centers_related_apiRequest, name='centers_related_apiRequest'),
    path('renew_plan/', views.renew_plan, name='renew_plan'),
    path('renew_plan_submit/', views.renew_plan_submit, name='renew_plan_submit'),
    path('subscription-plans/', subscription_plans, name='subscription_plans'),
    path('basic-plan/', views.basic_plan, name='basic_plan'),
    path('standard-plan/', views.standard_plan, name='standard_plan'),
    path('premium-plan/', views.premium_plan, name='premium_plan'),
    path('assign_plan/', assign_plan, name='assign_plan'),
    path('customer_authorization/<int:pk>/', customer_authorization, name='customer_authorization'),
    path('view_invoice/<str:pk>/', views.view_invoice, name = "view_invoice"),
]

crm/crmApp/forms.py
from django import forms

from django import forms
from .models import Center,CustomUser
class UserCreationForm(forms.ModelForm):
    confirmPassword = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'phoneNumber', 'role', 'password', 'blocked', 'center']
        widgets = {
            'password': forms.PasswordInput(),
        }

    # Override the save method to handle center assignment
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
            self.save_m2m()  # Required for saving ManyToMany fields
        return user

    def clean_confirmPassword(self):
        password = self.cleaned_data.get("password")
        confirmPassword = self.cleaned_data.get("confirmPassword")
        if password and confirmPassword and password != confirmPassword:
            raise forms.ValidationError("Passwords do not match")
        return confirmPassword

    # Override the __init__ method to dynamically set the queryset for the center field
    def __init__(self, *args, **kwargs):
        center_queryset = kwargs.pop('center_queryset', None)
        super().__init__(*args, **kwargs)
        if center_queryset is not None:
            self.fields['center'].queryset = center_queryset

crm/crmApp/views.py
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse
import requests
import os
from django.http import FileResponse
from .models import APIRequest, AdditionCharge, Booking, Center, Payment, Plans, Refund, Validity
from datetime import datetime, timedelta
from django.db.models import Sum
from .models import Refund
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
import json
import os
from amadeus import Client, ResponseError, Location
import amadeus
from amadeus import Client as AmadeusClient
import logging
from .models import Sale
from django.db.models import Sum
from .models import Chargeback,Center
from django.contrib.auth import get_user_model
from django.http import HttpResponseBadRequest
from .models import Invoice
import uuid
import random
from django.core.serializers import serialize
from pprint import pprint
from django.core.files.storage import FileSystemStorage
from dropbox_sign import \
    ApiClient, ApiException, Configuration, apis, models

from django.db.models.signals import post_migrate
from django.dispatch import receiver
from django.contrib.sessions.models import Session

configuration = Configuration(
    # Configure HTTP basic authorization: api_key
    username="8b0a24b667d452502026dde34a7e83e7dc821a6a6e935df11f2af2bbe023ad39",

    # or, configure Bearer (JWT) authorization: oauth2
    # access_token="YOUR_ACCESS_TOKEN",
)


logger = logging.getLogger(__name__)
    
CLIENT_ID = os.environ.get('AMADEUS_CLIENT_ID','')
CLIENT_SECRET_ID = os.environ.get('AMADEUS_CLIENT_SECRET','')

amadeus = Client(
    client_id = CLIENT_ID,
    client_secret = CLIENT_SECRET_ID
)

@receiver(post_migrate)
def create_main_center(sender, **kwargs):
    if sender.name == get_user_model()._meta.app_label:
        main_center, created = Center.objects.get_or_create(
            name='Main',
            email='',
            address='',
            phone='',
            contact_person='Admin',
            status='active'
        )
        if created:
            print('Main center created successfully.')



def get_location_suggestions(request):
    print("inside this ")
    keyword = request.GET.get('keyword', '')
    amadeus = AmadeusClient(
        client_id=os.environ.get('AMADEUS_CLIENT_ID', ''),
        client_secret=os.environ.get('AMADEUS_CLIENT_SECRET', '')
    )

    try:
        response = amadeus.reference_data.locations.get(keyword=keyword, subType='AIRPORT')
        term = "location and iataCode"
        requestCounter(request.user.center,term)
        print(response)
        locations = []
        for location in response.data:
            locations.append({
                'name': location['name'],
                'iataCode': location['iataCode'],
                'cityName': location['address']['cityName'],
                'airportName': location['name']
            })

        return JsonResponse({'locations': locations})
    except Exception as e:
        return JsonResponse({'error': str(e)})



def flight_results(request):
    if request.method == 'GET':
        # Get form data
        from_location = request.GET.get('from')
        to_location = request.GET.get('to')
        departure_date = request.GET.get('departureDate')
        return_date = request.GET.get('returnDate')
        print("return",return_date)
        adults = request.GET.get('adult')
        child = request.GET.get('child')
        infants = request.GET.get('infant')
        class_type = request.GET.get('flightClass')

        print("From Location:", from_location)
        print("To Location:", to_location)
        print("Departure Date:", departure_date)
        print("Adults:", adults)
        print("Child:", child)
        print("Infants:", infants)
        print("Class Type:", class_type)

        # Query Amadeus for flight data
        try:
            print("inside try")
            if return_date == "":
                response = amadeus.shopping.flight_offers_search.get(
                originLocationCode=from_location,
                destinationLocationCode=to_location,
                departureDate=departure_date,
                adults=adults,
                children=child,
                infants=infants,
                travelClass=class_type,
                currencyCode = 'USD'
                ).data
                term = "one way flight search"
                requestCounter(request.user.center,term)
                # Store the response as JSON format
                context = {
                    "flights" : response,
                    "flights1" : json.dumps(response),

                }
                file_path = "temp.txt"
                with open(file_path, "w") as file:
                    json.dump(context, file, indent= 4)
                # with open(file_path, "r") as file:
                #     context = json.load(file)
                return render(request, 'result1.html', context)

            else:
                response = amadeus.shopping.flight_offers_search.get(
                originLocationCode=from_location,
                destinationLocationCode=to_location,
                departureDate=departure_date,
                adults=adults,
                children=child,
                infants=infants,
                travelClass=class_type,
                currencyCode = 'USD'
                ).data
                term = "round trip"
                requestCounter(request.user.center,term)
                response_return = amadeus.shopping.flight_offers_search.get(
                originLocationCode=to_location,
                destinationLocationCode=from_location,
                departureDate=return_date,
                adults=adults,
                children=child,
                infants=infants,
                travelClass=class_type,
                currencyCode = 'USD'
                ).data
                requestCounter(request.user.center,term)

                # Store the response as JSON format
                context = {
                    "flights_departure" : response,
                    "flights_return": response_return,
                    "flights_departure1" : json.dumps(response),
                    "flights_return1" : json.dumps(response_return),
                }
                print(context)
                file_path = "round.txt"
                with open(file_path, "w") as file:
                    json.dump(context, file, indent= 4)
                # with open(file_path, "r") as file:
                #     context = json.load(file)
            # Pass the stringified JSON data to the template
            # print(context)
                return render(request, 'roundtrip.html', context)
        except ResponseError as error:
            # print(error["error"])
            return render(request, 'error.html', {'error': error.response.result["errors"]})
    else:
        return render(request, 'result1.html')
    
# def flight_results(request):
#     from_location = request.GET.get('fromLocation', '')
#     to_location = request.GET.get('toLocation', '')
#     departure_date = request.GET.get('departureDate', '')
#     return_date = request.GET.get('returnDate', '')
#     trip_type = request.GET.get('tripType', 'roundTrip')
#     flight_class = request.GET.get('flightClass', 'economy')
#     passenger_count = request.GET.get('passengerCount', '1')

#     amadeus = AmadeusClient(
#         client_id=os.environ.get('AMADEUS_CLIENT_ID', ''),
#         client_secret=os.environ.get('AMADEUS_CLIENT_SECRET', '')
#     )

#     try:
#         response = amadeus.shopping.flight_offers_search.get(
#             originLocationCode=from_location,
#             destinationLocationCode=to_location,
#             departureDate=departure_date,
#             returnDate=return_date if trip_type == 'roundTrip' else None,
#             adults=int(passenger_count),
#             travelClass=flight_class
#         )

#         flights = response.data
#         print(flights)  # For debugging purposes

#         # Convert flights data to JSON format
#         flights_json = json.dumps(flights)

#         return render(request, 'result.html', {'flights_json': flights_json})
#     except Exception as e:
#         return render(request, 'result.html', {'error': str(e)})

# def flight_book(request):
#     return render(request, "base.html")

from decimal import Decimal

from django.db.models import Case, Value, When

def total_booking(request):
    if request.user.is_superuser:
        original = Booking.objects.filter(status__in=['inprocess', 'rejected', 'confirmed', 'cancelled'])
        agents = CustomUser.objects.filter(role='agent')
        confirmed_bookings = original.filter(status='confirmed')

        total_price = Decimal(0.0)
        total_mco = Decimal(0.0)
        for booking in confirmed_bookings:
            total_price += Decimal(booking.price)
        
        total_revenue = total_price + total_mco
        # Rounding to two decimal points
        total_price_str = "${:.2f}".format(round(total_price, 2))
        total_mco_str = "${:.2f}".format(round(total_mco, 2))
        total_revenue_str = "${:.2f}".format(round(total_revenue, 2))

        context = {
            "original": original,
            "length": original.count(),
            "total_price": total_price_str,
            "total_mco": total_mco_str,
            "total_revenue": total_revenue_str,
            "agents": agents
        }
        return render(request, "total_booking.html", context)
    else:
        original = Booking.objects.filter(status__in=['inprocess', 'rejected', 'confirmed', 'cancelled'], center=request.user.center)
        # Reorder queryset to place entries with center name "Main" at the top
        original = original.annotate(
            is_main=Case(
                When(center__name='Main', then=Value(1)),
                default=Value(0),

crm/crmApp/templates/chargeback.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<nav class="navbar navbar-expand-lg navbar-light  mb-2">
    <div class="container-fluid">

        <!-- Navbar Brand and Description -->
        <div class="container" style="width: 100%; ">
          
                <a class="navbar-brand" href="#" style="font-size: 1rem;"><b>Welcome Chargeback</b></a>
                <p style="font-size: 0.8rem; color: #67748E;">This is where you can manage your tasks and view important information.</p>
       
        </div>

        <!-- Navbar Toggler Button -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar Links -->
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <img src="{% static 'assets/search.png' %}" style="width: 1.2rem" class="" alt="search">
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <img src="{% static 'assets/message.png' %}" style="width: 1.2rem" class="" alt="message">
                    </a>
                </li>
                <li class="nav-item">
                    {% for chargeback in pending_chargebacks %}
                    <span class="position-relative" style="cursor: pointer;" onclick="showNotification('{{ forloop.counter }}')">
                        <i class="fas fa-bell position-relative" style="cursor: pointer; width: 1.2rem;" onclick="showNotification('{{ forloop.counter }}')"></i>
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill text-dark mt-1">
                            {{ forloop.counter }}
                        </span>
                    </span>
                    {% endfor %}
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <img src="{% static 'assets/setting.png' %}" style="width: 1.2rem" class="" alt="total-users">
                    </a>
                </li>
                <li class="nav-item" style="margin-top: 3%; border: none; cursor: pointer;" onmouseover="this.style.backgroundColor='#3180ff';" onmouseout="this.style.backgroundColor='#f3f6fb';">
                    <div class="d-flex align-items-center">
                        <i class="fas fa-user-circle fa-lg"></i>
                        <p class="mb-0 ml-2 px-2" style="font-weight: bold; font-size: large;">{{ request.user.username }}</p>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
<h1 class="text-center mt-6">CRM <span>Dash</span>board - Chargeback</h1>
{% if messages %}
    <div id="successMessage" class="container">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}


<script>
    // Wait for three seconds before hiding the success message and optionally redirecting or refreshing the page
    setTimeout(function() {
        document.getElementById("successMessage").style.display = "none";
        document.getElementById("chargebackForm").reset();  // Clear the form
        // Optionally redirect or refresh the page after three seconds
        
    }, 3000);
</script>

<!-- chargeback_form.html -->
<button class="shadow-lg" id="showFormButton" style="height:5%;border:none; background-color:#3F88BD; color:white;">Add chargeback record</button>

<div id="formContainer" style="display: none;">
<!-- chargeback_form.html -->
<form method="post" action="{% url 'crmApp:submit_chargeback' %}" id="chargebackForm" class="row g-3">
    {% csrf_token %}

    <div class="col-md-3">
        <label for="booking_confirmation_no" class="form-label">Booking Confirmation No:</label>
        <input type="text" class="form-control" id="booking_confirmation_no" name="booking_confirmation_no">
    </div>

    <div class="col-md-3">
        <label for="reason" class="form-label">Reason:</label>
        <input type="text" class="form-control" id="reason" name="reason">
    </div>

    <div class="col-md-3">
        <label for="chargeback_received_date" class="form-label">Chargeback Received Date:</label>
        <input type="date" class="form-control" id="chargeback_received_date" name="chargeback_received_date">
    </div>

    <div class="col-md-3" style="margin-top:4%;">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>


</div>

<script>
    document.getElementById('showFormButton').addEventListener('click', function() {
        var formContainer = document.getElementById('formContainer');
        if (formContainer.style.display === 'none') {
            formContainer.style.display = 'block';
        } else {
            formContainer.style.display = 'none';
        }
    });
</script>




<!-- Total Chargebacks Card -->
<div class="card mt-3 shadow" style="width:30%;">
    <div class="card-header" style= "background: linear-gradient(to right, #020024, #090979, #05113d); color: white;">
        <h6 class="card-title">Total Chargebacks</h6>
    </div>
    <div class="card-body">
        <p class="card-text">${{ total_chargeback_amount }}</p>
    </div>
</div>
<!-- Top 5 Highest Chargebacks -->
<div class="card mt-3 shadow" style="width:30%;">
    <div class="card-header" style="background: linear-gradient(to right, #020024, #090979, #05113d); color: white;">
        <h6 class="card-title">Top 5 Highest Chargebacks</h6>
    </div>
    <div class="card-body">
        <ul style="font-size: 0.8rem">
            {% for chargeback in highest_chargebacks %}
            <li>{{ chargeback.Booking.passenger_name }} - ${{ chargeback.Booking.price }}</li>
            {% endfor %}
        </ul>
    </div>
</div>



<main class="container mt-6">
    <div class="row mt-5" style="background-color:white;">
    <h6>Chargeback table</h6>
        <!-- Table for Chargebacks -->
        <div class="col-md-12">
            <div class="table-responsive">
                <table style="border-color:#74c9f7ab; width:170%">
                    <thead style="background-color:#EAF2FF; border:2px solid white; font-size: 0.8rem;">
                        <tr>
                            {% comment %} <th>Sl No</th> {% endcomment %}
                            <th>Booking Id</th>
                            <th>Lead Agent</th>
                            <th>Booking Date</th>
                            <th>Customer Name</th>
                            <th>Customer Ph No</th>
                            <th>Email Address</th>
                            <th>Credit Card No</th>
                            <th>Confirmation Mail Status</th>
                            <th>Reason</th>
                            <th>Chargeback Recieved Date</th>
                            <th>Chargeback Status</th>
                            <th>Chargeback Status</th>
                            <th>Chargeback Lead Status</th>
                            <th>Chargeback Lead Status</th>
                            <th>Center</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Chargeback entries here -->
                        {% for chargeback in chargebacks %}
                        <tr>
                            {% comment %} <td>{{ forloop.counter }}</td> {% endcomment %}
                            <td style="font-weight: bolder; color: Blue; cursor: pointer" onclick="viewBooking('{{ chargeback.Booking.booking_id }}')">{{ chargeback.Booking.booking_id }}</td>
                            <td>{{chargeback.Booking.lead_agent.username}}</td>
                            <td>{{ chargeback.Booking.change_date }}</td>
                            <td style="width: 10rem;">{{ chargeback.Booking.passenger_name }}</td>
                            <td style="width: 10rem;">{{ chargeback.Booking.phone_number }}</td>
                            <td style="width: 10rem;">{{ chargeback.Booking.email }}</td>
                            <td style="width: 10rem;">{{ chargeback.Booking.card_number }}</td>
                            <td>{{ chargeback.confirmation_mail_status }}</td>
                            <td>{{ chargeback.reason }}</td>
                            <td>{{ chargeback.chargeback_received_date }}</td>
                            <td>{{ chargeback.chargeback_status }}</td>
                            <td>
                                <form id="chargeback_form_stat{{ chargeback.pk }}" method="post" action="{% url 'crmApp:update_chargeback_status' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="chargeback_id" value="{{ chargeback.pk }}">
                                    <select name="chargeback_status" onchange="confirmChangeStatus('chargeback_form_stat{{ chargeback.pk }}', this)">
                                        <option value="pending" {% if chargeback.chargeback_status == "pending" %} selected {% endif %}>Pending</option>
                                        <option value="accepted" {% if chargeback.chargeback_status == "accepted" %} selected {% endif %}>Accept</option>
                                        <option value="disputed" {% if chargeback.chargeback_status == "disputed" %} selected {% endif %}>Dispute</option>
                                    </select>
                                </form>
                            </td>
                            <td>{{ chargeback.chargeback_lead_status }}</td>
                            <td>
                                <form id="chargeback_form_{{ chargeback.pk }}" method="post" action="{% url 'crmApp:update_chargeback_lead_status' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="chargeback_id" value="{{ chargeback.pk }}">
                                    <select name="chargeback_lead_status" onchange="confirmChange('chargeback_form_{{ chargeback.pk }}', this)">
                                        <option value="pending" {% if chargeback.chargeback_lead_status == "pending" %} selected {% endif %}>Pending</option>
                                        <option value="won" {% if chargeback.chargeback_lead_status == "won" %} selected {% endif %}>Won</option>
                                        <option value="loss" {% if chargeback.chargeback_lead_status == "loss" %} selected {% endif %}>Loss</option>
                                    </select>
                                </form>
                            </td>
                            <td>{{ chargeback.Booking.center }}</td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>
<script>
    function confirmChangeStatus(formId, selectElement) {
        var confirmation = confirm("Are you sure you want to change the chargeback status?");
        if (confirmation) {
            document.getElementById(formId).submit();
        } else {
            // Reset select option to the original value
            var originalValue = '{{ chargeback.chargeback_status }}';
            for (var i = 0; i < selectElement.options.length; i++) {
                if (selectElement.options[i].value === originalValue) {
                    selectElement.selectedIndex = i;
                    break;
                }
            }
        }
    }
</script>

<script>
    function confirmChange(formId, selectElement) {
        var confirmation = confirm("Are you sure you want to change the chargeback status?");
        if (confirmation) {
            document.getElementById(formId).submit();
        } else {
            // Reset select option to the original value
            var originalValue = '{{ chargeback.chargeback_lead_status }}';
            for (var i = 0; i < selectElement.options.length; i++) {
                if (selectElement.options[i].value === originalValue) {
                    selectElement.selectedIndex = i;
                    break;
                }
            }
        }
    }
</script>
<!-- Form to submit booking ID -->
<form id="bookingForm" method="post" action="{% url 'crmApp:related_booking' %}" style="display: none;">
    {% csrf_token %}
    <input type="hidden" id="bookingIdInput" name="booking_id">
</form>
<script>
    function viewBooking(bookingId) {
        console.log(bookingId)
        document.getElementById("bookingIdInput").value = bookingId;
        document.getElementById('bookingForm').submit();
}
</script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoJtKh7z7lGz7fuP4F8nfdFvAOA6Gg/z6Y6J6XqqyGXYM2ntXU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@6.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pzjw8f+ua7Kw1TIq0v8FqFjcJ6pajs/rfdfs3SO+kD4Ck6BdPtF+to8xMp9MvcJ4" crossorigin="anonymous"></script>
{% endblock %}

crm/crmApp/templates/signature_request.html
<!-- signature_request.html -->

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>
  